export const paths = {
  home: '/',
  tours: '/tours',
  tour: (slug: string) => `/tours/${slug}`,
  destinations: '/destinations',
  destination: (slug: string) => `/destinations/${slug}`,
  vehicles: '/vehicles',
  about: '/about',
  gallery: '/gallery',
  reviews: '/reviews',
  writeAReview: '/write-a-review',
  contact: '/contact',
  inquiry: '/inquiry',
  privacy: '/privacy',
  terms: '/terms',
  admin: {
    login: '/admin/login',
    root: '/admin',
    tours: '/admin/tours',
    destinations: '/admin/destinations',
    vehicles: '/admin/vehicles',
    reviews: '/admin/reviews',
    gallery: '/admin/gallery',
    inquiries: '/admin/inquiries',
    settings: '/admin/settings',
  },
} as const
